### PR TITLE
Added bower.json.

### PR DESCRIPTION
**Pull request by estoner**
Hi, I ran into some issues installing your plugin without a valid bower.json, so I thought I'd offer you a placeholder if you're interested.

Bower can install without the bower.json config file if you just specify a git repo/commit to pull from, but then you can't programmatically make sure that your dependencies are all up to date when you run a build.

### CODE REVIEW

**Comment by ryanto** [comment]
Thanks! you the man.

**Comment by estoner** [comment]
No problem at all!  Thanks for the merge.

**Comment by estoner** [comment]
Hmm, it looks like bower also needs a version tag up on GitHub for it to show in the registry, do you mind tagging that last commit?

Should just be:

```
git tag v0.1.0
git push origin -a
```

**Comment by ryanto** [comment]
All set

**Pull request merged**
